export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const LOGGED_SUCCESS = 'LOGGED_SUCCESS';
export const GET_USER_UPDATED_SUCCESS = 'GET_USER_UPDATED_SUCCESS';

export const TUIT_RECEIVED_SUCCESS = 'TUIT_RECEIVED_SUCCESS';
export const USER_TUITS_RECEIVED_SUCCESS = 'USER_TUITS_RECEIVED_SUCCESS';
export const GETTING_ALL_TUITS_SUCCESS = 'GETTING_ALL_TUITS_SUCCESS';
export const GETTING_ALL_USERS_RELATED_SUCCESS =
  'GETTING_ALL_USERS_RELATED_SUCCESS';
